### ISSUE TITLE
Build for browsers

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/mdsf#26]

**Comment by belochub** [comment]
Done in https://github.com/metarhia/mdsf/pull/3.

**Comment by tshemsedinov** [comment]
But why we don't use webpack to create a single bundle?

**Comment by aqrln** [comment]
@tshemsedinov because it will be bundled with webpack during an application build anyway, and putting a bundle inside another bundle (hence, two copies of the module system, polyfills and helpers, common modules that won't be possible to deduplicate, etc) is just extra overhead for no reason. We might build UMD bundles for the user-facing libraries (like we did in JSTP — mainly because the test application in Impress doesn't have a build step), but I see no use case for UMD bundles in libraries like mdsf.
